apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: csoc-platform
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  description: "CSOC platform components: KRO, RGDs, CAPI+CAPO controllers. Highly restricted."
  sourceRepos:
    - https://github.com/jayadeyemi/js-poc-csoc-bootstrap
    - https://github.com/jayadeyemi/js-poc-csoc-platform-apis
    - registry.k8s.io/kro/charts
    - https://argoproj.github.io/argo-helm
    - https://kubernetes-sigs.github.io/cluster-api-operator
    - https://charts.jetstack.io
    - https://github.com/k-orc/openstack-resource-controller
  destinations:
    - server: https://kubernetes.default.svc
      namespace: kro-system
    - server: https://kubernetes.default.svc
      namespace: capi-system
    - server: https://kubernetes.default.svc
      namespace: capo-system
    - server: https://kubernetes.default.svc
      namespace: capi-kubeadm-control-plane-system
    - server: https://kubernetes.default.svc
      namespace: capi-kubeadm-bootstrap-system
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: cluster-registration
    - server: https://kubernetes.default.svc
      namespace: spokeclusters
    - server: https://kubernetes.default.svc
      namespace: capi-operator-system
    - server: https://kubernetes.default.svc
      namespace: cert-manager
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: caaph-system
    - server: https://kubernetes.default.svc
      namespace: orc-system
  clusterResourceWhitelist:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: kro.run
      kind: ResourceGraphDefinition
    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionPolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionPolicyBinding
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
