apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rgds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  description: "CSOC controllers and ResourceGraphDefinitions."
  sourceRepos:
    - https://github.com/jayadeyemi/js-poc-csoc-bootstrap
    - https://github.com/jayadeyemi/js-poc-csoc-app-catalog
    - registry.k8s.io/kro/charts
    - https://argoproj.github.io/argo-helm
    - https://kubernetes-sigs.github.io/cluster-api-operator
    - https://charts.jetstack.io
    - https://github.com/k-orc/openstack-resource-controller
  destinations:
    - server: https://kubernetes.default.svc
      namespace: kro-system
    - server: https://kubernetes.default.svc
      namespace: capi-system
    - server: https://kubernetes.default.svc
      namespace: capo-system
    - server: https://kubernetes.default.svc
      namespace: capi-kubeadm-control-plane-system
    - server: https://kubernetes.default.svc
      namespace: capi-kubeadm-bootstrap-system
    - server: https://kubernetes.default.svc
      namespace: argocd
    - server: https://kubernetes.default.svc
      namespace: capi-operator-system
    - server: https://kubernetes.default.svc
      namespace: cert-manager
    - server: https://kubernetes.default.svc
      namespace: kube-system
    - server: https://kubernetes.default.svc
      namespace: caaph-system
    - server: https://kubernetes.default.svc
      namespace: orc-system
    - server: https://kubernetes.default.svc
      namespace: "spokeclusters-*"
    - server: https://kubernetes.default.svc
      namespace: cluster-registration
  clusterResourceWhitelist:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
    - group: kro.run
      kind: ResourceGraphDefinition
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionPolicy
    - group: admissionregistration.k8s.io
      kind: ValidatingAdmissionPolicyBinding
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: argoproj.io
      kind: Application
    - group: argoproj.io
      kind: AppProject
    - group: cert-manager.io
      kind: Certificate
    - group: cert-manager.io
      kind: Issuer
    - group: operator.cluster.x-k8s.io
      kind: AddonProvider
    - group: operator.cluster.x-k8s.io
      kind: BootstrapProvider
    - group: operator.cluster.x-k8s.io
      kind: ControlPlaneProvider
    - group: operator.cluster.x-k8s.io
      kind: CoreProvider
    - group: operator.cluster.x-k8s.io
      kind: InfrastructureProvider
    - group: ""
      kind: ServiceAccount
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: batch
      kind: Job
    - group: batch
      kind: CronJob
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
