apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csoc-app-of-apps
  namespace: argocd
spec:
  project: rgds
  source:
    repoURL: https://github.com/jayadeyemi/js-poc-csoc-bootstrap
    targetRevision: environment/dev
    path: .
    directory:
      recurse: true
      include: "{argocd/projects/*.yaml,argocd/environments/dev/apps/*.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
