# Existing development CSOC. These ownership paths intentionally point to the
# already-provisioned js2-mgmt-cluster-2 and must not be reused by production.
CSOC_PROFILE_NAME=dev
CSOC_FLEET_ENABLED=true
CSOC_BOOTSTRAP_REVISION=master
CSOC_CATALOG_REVISION=main
CSOC_FLEET_REVISION=main
CSOC_ARGO_ROOT_MANIFEST_REL=argocd/app-of-apps.yaml

MAGNUM_CLUSTER_NAME=${MAGNUM_CLUSTER_NAME:-js2-mgmt-cluster-2}
MAGNUM_STATE_FILE_REL=.state/magnum-cluster-2.json
MAGNUM_KUBECONFIG_DIR_REL=.state/kubeconfigs
MAGNUM_MASTER_COUNT=${MAGNUM_MASTER_COUNT:-1}
MAGNUM_MASTER_FLAVOR=${MAGNUM_MASTER_FLAVOR:-m3.quad}
MAGNUM_NODE_COUNT=${MAGNUM_NODE_COUNT:-1}
MAGNUM_WORKER_FLAVOR=${MAGNUM_WORKER_FLAVOR:-m3.quad}
MAGNUM_MIN_NODE_COUNT=${MAGNUM_MIN_NODE_COUNT:-1}
MAGNUM_MAX_NODE_COUNT=${MAGNUM_MAX_NODE_COUNT:-2}
MAGNUM_EXPECTED_INITIAL_NODES=${MAGNUM_EXPECTED_INITIAL_NODES:-2}
