# Production CSOC. It owns production tuples and only those development tuples
# explicitly routed away from staging in the fleet ownership registry.
CSOC_PROFILE_NAME=prod
CSOC_FLEET_ENABLED=true
CSOC_BOOTSTRAP_REVISION=environment/prod
CSOC_CATALOG_REVISION=environment/prod
CSOC_FLEET_REVISION=environment/prod
CSOC_ARGO_ROOT_MANIFEST_REL=iac/csoc/profiles/prod-app-of-apps.yaml
CSOC_APPLICATION_DIR_REL=argocd/environments/prod/apps
CSOC_FLEET_PATH=environments/prod

MAGNUM_CLUSTER_NAME=${MAGNUM_CLUSTER_NAME:-csoc-prod}
MAGNUM_STATE_FILE_REL=.state/csoc/prod/magnum-cluster.json
MAGNUM_KUBECONFIG_DIR_REL=.state/csoc/prod/kubeconfigs
MAGNUM_MASTER_COUNT=${MAGNUM_MASTER_COUNT:-3}
MAGNUM_MASTER_FLAVOR=${MAGNUM_MASTER_FLAVOR:-m3.small}
MAGNUM_NODE_COUNT=${MAGNUM_NODE_COUNT:-3}
MAGNUM_WORKER_FLAVOR=${MAGNUM_WORKER_FLAVOR:-m3.quad}
MAGNUM_BOOT_VOLUME_SIZE=${MAGNUM_BOOT_VOLUME_SIZE:-60}
MAGNUM_AUTO_SCALING_ENABLED=${MAGNUM_AUTO_SCALING_ENABLED:-false}
MAGNUM_MIN_NODE_COUNT=${MAGNUM_MIN_NODE_COUNT:-3}
MAGNUM_MAX_NODE_COUNT=${MAGNUM_MAX_NODE_COUNT:-3}
MAGNUM_EXPECTED_INITIAL_NODES=${MAGNUM_EXPECTED_INITIAL_NODES:-6}
