apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: capo-identity
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: csoc-platform
  source:
    repoURL: https://github.com/jayadeyemi/js-poc-csoc-bootstrap
    targetRevision: master
    path: controllers/capo-identity
  destination:
    server: https://kubernetes.default.svc
    namespace: capo-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
