apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csoc-controllers
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-50"
spec:
  project: rgds
  source:
    repoURL: https://github.com/jayadeyemi/js-poc-csoc-bootstrap
    targetRevision: master
    path: controllers
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
  revisionHistoryLimit: 3
