apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rgds
  namespace: argocd
  annotations:
    # RGDs must be deployed after KRO so KRO can compile them into CRDs
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: rgds
  source:
    repoURL: https://github.com/jayadeyemi/js-poc-csoc-app-catalog
    targetRevision: main
    path: rgds
  destination:
    server: https://kubernetes.default.svc
    namespace: kro-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
