apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: csoc-fleet
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: csoc-fleet
  source:
    repoURL: https://github.com/jayadeyemi/js-poc-csoc-fleet
    targetRevision: environment/staging
    path: accounts/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: kro-system
  syncPolicy:
    automated: {prune: false, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true, SkipDryRunOnMissingResource=true]
