apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rgds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  project: rgds
  source:
    repoURL: https://github.com/jayadeyemi/js-poc-csoc-app-catalog
    targetRevision: environment/staging
    path: rgds
  destination:
    server: https://kubernetes.default.svc
    namespace: kro-system
  syncPolicy:
    automated: {prune: false, selfHeal: true}
    syncOptions: [ServerSideApply=true, SkipDryRunOnMissingResource=true]
