#!/usr/bin/env bash
# Inner bootstrap pipeline; invoked inside the pinned management container.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
source "${REPO_ROOT}/scripts/lib/logging.bash"

log::step A "Validate the coordinated workspace"
bash "${REPO_ROOT}/scripts/tools/validate.sh"
log::step B "Preflight and provision the guide-exact Magnum cluster"
bash "${REPO_ROOT}/scripts/bootstrap/magnum/preflight.sh"
bash "${REPO_ROOT}/scripts/bootstrap/magnum/provision.sh"
log::step C "Wait for complete and HEALTHY Magnum state"
bash "${REPO_ROOT}/scripts/bootstrap/magnum/wait.sh"
log::step C "Reconcile default worker node-group bounds"
bash "${REPO_ROOT}/scripts/bootstrap/magnum/configure-nodegroup.sh"
log::step D "Retrieve certificate kubeconfig and verify the management cluster"
bash "${REPO_ROOT}/scripts/bootstrap/magnum/kubeconfig.sh"
bash "${REPO_ROOT}/scripts/bootstrap/magnum/verify.sh"
bash "${REPO_ROOT}/scripts/bootstrap/magnum/verify-autoscaling.sh"
log::step E "Install Argo CD"
bash "${REPO_ROOT}/scripts/bootstrap/argocd/install.sh"
log::step E "Manually validate manifests before enabling Argo reconciliation"
bash "${REPO_ROOT}/scripts/bootstrap/argocd/manual-smoke-test.sh"
log::step F "Inject only the restricted runtime OpenStack credential"
bash "${REPO_ROOT}/scripts/bootstrap/credentials/create-runtime-cloud-secret.sh"
log::step G "Apply App-of-Apps and wait for GitOps controllers"
bash "${REPO_ROOT}/scripts/bootstrap/argocd/bootstrap-apps.sh"
log::success "Bootstrap complete. Git is now the control plane."
